import tailwindcss from "@tailwindcss/vite";
import { foldkit } from "@foldkit/vite-plugin";
import { VitePWA } from "vite-plugin-pwa";
import { defineConfig } from "vite-plus";

// Deployed to GitHub Pages project site: https://mariusom.github.io/optio/
export default defineConfig(({ command, mode }) => {
  const bundledDev = command === "serve" && mode !== "test";
  const tailwind = tailwindcss();
  if (bundledDev) {
    // Vite+ 0.3.1 forwards this Vite-only hook to Rolldown's incompatible
    // hotUpdate hook (which has no server/environments). Bundled dev already
    // watches the source dependencies registered by Tailwind's transform.
    for (const plugin of tailwind) delete plugin.hotUpdate;
  }
  return defineConfig({
    experimental: { bundledDev },
    base: "/optio/",
    resolve: { alias: { "@": new URL("./src", import.meta.url).pathname } },
    server: {
      port: 60_001,
      allowedHosts: process.env.PUBLIC_URL ? [new URL(process.env.PUBLIC_URL).hostname] : [],
    },
    worker: { format: "es" },
    plugins: [
      ...tailwind,
      foldkit(),
      VitePWA({
        registerType: "autoUpdate",
        // PNG raster icons (generated by scripts/gen-icons.ts) are required for
        // install/prompt on iOS/Android; the SVG stays in index.html as favicon.
        includeAssets: ["icon.svg", "icon-180.png", "icon-192.png", "icon-512.png"],
        manifest: {
          name: "optio — offline time & motion studies",
          short_name: "optio",
          description:
            "Create time studies, record tasks, and export CSV. Works offline after initial loading. No account needed.",
          theme_color: "#f5f8f5",
          background_color: "#f5f8f5",
          display: "standalone",
          icons: [
            { src: "icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
            { src: "icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
            { src: "icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
          ],
        },
        workbox: {
          globPatterns: ["**/*.{js,css,html,svg,wasm}"],
        },
      }),
    ],
    optimizeDeps: {
      // Required by LiveStore's web adapter (see @livestore/adapter-web README)
      exclude: ["@livestore/wa-sqlite"],
      // The shared-worker entry bypasses dependency scanning. Keep its RPC/schema
      // runtime in the same optimized graph instead of mixing raw and bundled Effect.
      include: ["@livestore/adapter-web > @livestore/utils/effect"],
      // Avoid a waterfall of small shared dependency chunks over remote dev connections.
      // Also used by tests, which keep Vite's unbundled module/mocking pipeline.
      rolldownOptions: {
        output: {
          codeSplitting: {
            groups: [{ name: "vendor", test: /node_modules/ }],
          },
        },
      },
    },
  });
});
